version: '3.8'

services:
  postgres-test:
    image: timescale/timescaledb:latest-pg15
    container_name: tiris-postgres-test
    environment:
      POSTGRES_DB: tiris_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d tiris_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tiris-test-network

  redis-test:
    image: redis:7-alpine
    container_name: tiris-redis-test
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - tiris-test-network

  nats-test:
    image: nats:2.10-alpine
    container_name: tiris-nats-test
    command: [
      "--jetstream", 
      "--store_dir", "/data",
      "--max_memory_store", "1GB",
      "--max_file_store", "10GB"
    ]
    ports:
      - "4223:4222"  # Different port to avoid conflicts
      - "8223:8222"  # Management port
    volumes:
      - nats_test_data:/data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - tiris-test-network

  # Optional: Test database admin interface
  adminer-test:
    image: adminer:4.8.1
    container_name: tiris-adminer-test
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres-test
      ADMINER_DEFAULT_USERNAME: test_user
      ADMINER_DEFAULT_DB: tiris_test
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - tiris-test-network
    profiles:
      - admin

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local
  nats_test_data:
    driver: local

networks:
  tiris-test-network:
    driver: bridge
    name: tiris-test-network