# Tiris Portal - Frontend Application
# Serves the main user interface on www.dev.tiris.ai

services:
  portal:
    # Replace with your portal application image/build
    image: nginx:alpine  # Placeholder - replace with actual portal image
    container_name: tiris-portal
    restart: always
    ports:
      - "8081:80"  # Internal port mapping for reverse proxy
    volumes:
      # Mount your portal application files here
      - ./dist:/usr/share/nginx/html:ro  # Example for static files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      # Portal-specific environment variables
      - NODE_ENV=production
      - API_URL=https://backend.dev.tiris.ai
      - PORTAL_VERSION=1.0.0
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - tiris-portal-network

# Portal-specific volumes
volumes:
  portal-assets:
    driver: local

# Portal network
networks:
  tiris-portal-network:
    name: tiris-portal-network
    driver: bridge