#!/bin/bash

# API Testing Script for Tiris Backend
# 
# This script tests API authentication using JWT tokens.
# 
# IMPORTANT: This uses a JWT token for API authentication, NOT OAuth tokens.
# - JWT tokens are generated by scripts/generate-jwt-token.go
# - JWT tokens are used for all API requests (format: eyJ...)
# - OAuth tokens are stored in the database for provider integration
# 
# To get a fresh JWT token:
# 1. Create a test user: ./scripts/create-test-user.sh --name "Your Name"
# 2. Copy the JWT token from the output
# 3. Update the ACCESS_TOKEN variable below

# JWT Access Token for API Authentication
# This is a JWT token (3 parts separated by dots) that contains user claims
ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiN2U2YTg5ZTYtM2U0Ni00MWQzLWFlYzYtMjg1ZmQ5Mjg5ODNiIiwidXNlcm5hbWUiOiJhbGV4IiwiZW1haWwiOiJhbGV4QHRpcmlzLmxvY2FsIiwicm9sZSI6InVzZXIiLCJpc3MiOiJ0aXJpcy1iYWNrZW5kIiwic3ViIjoiN2U2YTg5ZTYtM2U0Ni00MWQzLWFlYzYtMjg1ZmQ5Mjg5ODNiIiwiZXhwIjoxNzg2OTk5NjQyLCJuYmYiOjE3NTU0NjM2NDIsImlhdCI6MTc1NTQ2MzY0Mn0.T-c21MuwByZ8aeaahM45eECZt9FNwB5JC1OcS1glee8

echo "🔧 Testing API Authentication with JWT Token"
echo "=============================================="
echo "Endpoint: GET /v1/users/me"
echo "Auth: Bearer JWT Token"
echo ""

# Make the API request
curl -H "Authorization: Bearer $ACCESS_TOKEN" \
     -H "Content-Type: application/json" \
     http://localhost:8080/v1/users/me

echo ""
echo ""
echo "📝 Notes:"
echo "- If you get 401 Unauthorized, the JWT token may be expired"
echo "- Create a new test user to get a fresh JWT token"
echo "- JWT tokens are different from OAuth tokens stored in the database"

