apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tiris-backend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tiris-backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}