{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tiris-backend.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tiris-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      {{- include "tiris-backend.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
    scheme: http
    honorLabels: true
    scrapeTimeout: 10s
{{- end }}