apiVersion: v1
kind: ConfigMap
metadata:
  name: tiris-backend-config
  namespace: tiris
data:
  # Application Configuration
  GIN_MODE: "release"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Database Configuration
  DB_HOST: "tiris-postgres-service"
  DB_PORT: "5432"
  DB_NAME: "tiris_prod"
  DB_USER: "tiris_user"
  DB_SSL_MODE: "require"
  DB_MAX_OPEN_CONNS: "25"
  DB_MAX_IDLE_CONNS: "5"
  DB_CONN_MAX_LIFETIME: "300"
  
  # NATS Configuration
  NATS_URL: "nats://tiris-nats-service:4222"
  NATS_MAX_RECONNECT: "10"
  NATS_RECONNECT_WAIT: "2s"
  
  # Redis Configuration
  REDIS_URL: "redis://tiris-redis-service:6379/0"
  REDIS_MAX_IDLE: "10"
  REDIS_MAX_ACTIVE: "20"
  REDIS_IDLE_TIMEOUT: "240s"
  
  # JWT Configuration
  JWT_EXPIRATION: "3600"
  REFRESH_EXPIRATION: "604800"
  
  # CORS Configuration
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  CORS_ALLOWED_HEADERS: "Origin,Content-Type,Accept,Authorization,X-Requested-With"
  
  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  RATE_LIMIT_BURST: "100"
  
  # Monitoring
  METRICS_ENABLED: "true"
  METRICS_PATH: "/metrics"
  HEALTH_CHECK_INTERVAL: "30s"
  
  # Container Settings
  WAIT_FOR_DB: "true"
  RUN_MIGRATIONS: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tiris-postgres-config
  namespace: tiris
data:
  POSTGRES_DB: "tiris_prod"
  POSTGRES_USER: "tiris_user"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tiris-redis-config
  namespace: tiris
data:
  REDIS_APPENDONLY: "yes"
  REDIS_MAXMEMORY: "512mb"
  REDIS_MAXMEMORY_POLICY: "allkeys-lru"